nginx/conf/default.conf
For correct document root configuration when installation bitrix installation is needed.
=> Add detection bitrixsetup.php. Issue #15

nginx/conf/default.conf, php/php.ini
=> Fix backup uploading problem issue #13

docker-compose.yml, mysql/my.cnf
#10 
Ошибочное копирование файлов с логами в папку bitrix.
=> fix timezone mysql

mysql/my.cnf
=> Исправлен запуск контейнера mysql

README.md
Данный образ может рабоать и с apache если указать это в настройках... добавил к описанию в ридми
=> Добавил информацию про apache

docker-compose.yml, nginx/conf/default.conf
Добавил и обкатал настройки для работы интернет магазина на bitrix
=> ЧПУ+client_max_body_size

nginx/Dockerfile, php7/php.ini
Проверил - все работает :) Магазин на виртуалке с 4GB памяти ставится без единых ошибок
=> Добавил памяти в php и поменял версию Nginx

README.md
Корректное отображение текста в спойлере
=> fix(readme) Правка спойлера

docker-compose.yml
Собственное решение для Issue #95
=> fix #95: Add adminer for manage db

apache/conf/conf.d/default.conf
Сорри за несколько веток в issue #93 :)
=> fix #93: Allow .htaccess for apache urls

.env_template, docker-compose.yml
Решает проблему #103, когда на одном хосте разворачивается несколько инстансов bitrixdock.
=> Added the ability to specify a project

nginx/conf/default.conf, nginx/conf/nginx.conf
- add ipv6 listen
- add speed options for listen directive
- add recommended `X-Content-Type-Options nosniff` header
- remove index.php from URL
- rewrite multiple slashes from URL in few situations, prevent their work in few another
- saner timeout and other Nginx defaults in `http` section
Please try to run that setup before merging, I don't expect any problems but I need another pair of hands trying it before it could be considered safe.
=> Update nginx configuration with better defaults

php74/Dockerfile
[Changelog](https://pecl.php.net/package-changelog.php?package=mcrypt&release=1.0.4).
=> bump mcrypt to 1.0.4

nginx/Dockerfile, nginx/conf/default.conf
=> Bump nginx to 1.18, remove http2 (as it is HTTPS only)

README.md
Also, fix the list at the end of the Readme.
=> add bitrix.infra example to readme

mysql/Dockerfile, nginx/Dockerfile, percona/Dockerfile, php56/Dockerfile, php71/Dockerfile, php73/Dockerfile, php74/Dockerfile, php80/Dockerfile, php80/php.ini
Добавил конфиг PHP8, пока без конфига xdebug, т.к. в 3 версии они поменяли свои конфиги, если руки дорастут - запилю позже
В Dockerfile'ах заменил ADD на COPY согластно бест практисам Docker https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy
=> Базовый конфиг PHP8 + мелкие правки

.env_template, docker-compose.yml
Не знаю вам зайдет или нет:
Имя проекта к названию контейнера можно добавлять при помощи нативной переменной COMPOSE_PROJECT_NAME
https://docs.docker.com/compose/reference/envvars/#compose_project_name
+ увидел что в блоке с томами прописан нигде не использующийся вольюм "site"
=> PROJECT NAME

php74/Dockerfile, php80/Dockerfile
Они поменяли дефолтное тегирование образов
https://github.com/phpdocker-io/base-images#note-changes-to-php-image-locations-at-docker-hub
=> Новое расположение образов для PHP

install.sh
На чистой установке была проблема с установкой гита (без apt update), а так же была проблема в source (ее нет в sh), но она не нужна, т.к. после копирования бинарника команда docker-compose доступна в баше сразу. Плюс обновил docker-compose
=> Фикс скриптов

Makefile
console-root - Работа с консолью из под пользователя root
console-mysql - Вход в консоль MySQL из под пользователя по умолчанию из .env
console-mysql-root - Вход в консоль MySQL из под пользователя root
stop - Останавливаем контейнеры
ps - Список контейнеров
```
help                           This help
console                        Run bash (PHP) from "www-data"
console-root                   Run bash (PHP) from "root"
console-mysql                  Log in to the MySQL console from default user
console-mysql-root             Log in to the MySQL console from "root"
up                             Up Docker-project
down                           Down Docker-project
stop                           Stop Docker-project
build                          Build Docker-project
ps …
```
=> Добавлены новые команды в Makefile

.env_template, php82/Dockerfile, php82/php.ini
Привет
На 8.2 пыхе работает 😁 Жду первого февраля, битриксоиды обещают офф поддержку 8.1 и выше. В тикете сказали, что 8.2 тож поддерживают, а вот когда будет новая BitrixVM с поддержкой 8.2 - хз
=> Добавлен конфиг PHP 8.2

nginx/Dockerfile
До актуальной поддерживаемой в BitrixVM
=> Обновлена версия nginx

README.md
It was updated recently and readme had outdated information.
=> Bump bitrix.infra description to mention PHP 8.2

.gitignore, README.md, install.sh
Небольшие правки литературки))
=> Мелкие правки

.env_template, docker-compose.yml, nginx/conf/default.conf, percona/Dockerfile, www/index.html
Предлагаю следующим образом упростить первоначальную конфигурацию
Как справедливо заметили в этом issue https://github.com/bitrixdock/bitrixdock/issues/185 многие юзеры путаются и ловят ошибку "No input file specified"
=> Изменение изначальной директории сайта

.env_template, php/php83/Dockerfile, php/php83/php.ini
В новой версии BitrixVM добавили поддержку 8.3 https://dev.1c-bitrix.ru/learning/course/index.php?COURSE_ID=32&CHAPTER_ID=011219
На своих продах еще не обновлял, но девы крутятся на 8.3 без ошибок 😇
=> Добавлен образ PHP 8.3

php/php74/php.ini
=> Фикс двойного подключения mcrypt

apache/Dockerfile, mysql/Dockerfile, nginx/Dockerfile, percona/Dockerfile, php/php56/Dockerfile, php/php71/Dockerfile, php/php73/Dockerfile, php/php74/Dockerfile, php/php80/Dockerfile, php/php81/Dockerfile, php/php82/Dockerfile, php/php83/Dockerfile
Might be useful for users and dependabot:
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#docker
=> Add image source information to Dockerfiles

.github/workflows/test-docker-build.yml
This insanity was written mostly by ChatGPT. I've tested it, and after many iterations of trial and error, it works.
=> Add GitHub CI action to test building docker images once files are changed

.github/dependabot.yml
Please merge only after #215.
After the merge, new PRs would be created:
https://github.com/paskal/bitrixdock/pull/3
https://github.com/paskal/bitrixdock/pull/4
=> Add dependabot updates for updatable docker images and GitHub actions

.github/dependabot.yml
They turned out to be useless.
=> Remove dockerfile updates from dependabot

.github/workflows/test-docker-build.yml
Забыл про тесты, когда добавлял php 8.4
=> Добавлены тесты для PHP 8.4

README.md, docker-compose.yml, nginx/conf/default.conf, nginx/conf/nginx.conf
- Добавлен профиль "admin" для Adminer сервиса
- Добавлен профиль "push" для push-server-sub, push-server-pub и redis
- Обновлена документация с информацией о новых профилях
Мерджить после #241.
=> feat: добавлены Docker Compose профили для сервисов

docker-compose.yml
1e95d2acbef3b97693c590ce6e276e1da723193e к вопросу о "с каких пор решение конфликтов в гите стало чем-то сложным? 😆"
=> remove extra lines added by mistake

README.md, workspace/Dockerfile, workspace/php.ini
Фикс сборки, добавлены инструменты
=> Доработки workspace контейнера

workspace/Dockerfile
Фикс для https://github.com/bitrixdock/bitrixdock/issues/262
=> Фикс ошибки если нет пользователя
