apache/conf/httpd.conf

Разрешил AllowOverride в конфигурации с APACHE
Иначе выдавало access denied при обращении к сайту на битриксе

AllowOverride для конфигурации с апачем

---

nginx/conf/default.conf

Nginx [resolves](http://nginx.org/en/docs/http/request_processing.html) deeper non-regexp match and then first regexp match if it's present. That means that `~ /upload/` on the top of the file is hitting all `/upload/` URLs overriding all regex location with `/upload` is below it.
Also, this PR adds `.ht` ignore to ignore files like `.htaccess`, and hide `.gitignore` and `.git` behind `403` status code not only in the root of the repo but also in any subdirectory.
`/upload/support/not_image/.htaccess` URL is accessible and served by `/upload` endpoint
`/upload/CNext/516/5164fd8971f9b62a48681acbe3b942ed.png` served by `/upload/ ` endpoint and not receiving proper cashe headers from location `~* ^.+\.(jpg|jpeg|gif|png|...`
`/upload/support/not_image/.htaccess` URL returns `403` …

[nginx] fix static resources and denies serving

---

nginx/conf/default.conf

[PHP SERVER_NAME](https://www.php.net/manual/en/reserved.variables.server.php) variable set to `§host` (equal to `HTTP_HOST` out of the box behavior) is a hard requirement for the multi-domain regional setup of [aspro.next](https://aspro.ru/marketplace/solutions/aspro.next/) to work, I can't think of this change breaking something but I do think that having it out of the box might be a good thing for everyone.
Feel free to reject if you can come up with the reasons why this might be harmful.

Add server_name = $host to work in multi-domain env

---

nginx/conf/default.conf

This PR:
1. Gets all deny conditions into single regexp, and adds `/bitrix/updates`, `/upload/1c_exchange` and `/logs/` to these conditions as they should be denied in apache2 according to `.htaccess` files but are not denied in the current configuration;
1. Moves .php Nginx regex location to the end of the file to prevent restricted things like `http://hostname/bitrix/updates/update_m1590470536/main/jscore.php` from working;
1. Moves static resources serving to below the deny rule, as otherwise they will be served even from the denied folder: deny regex need to stay first.

Clarify restrictions, sort regex locations to restrict go first

---

php74/Dockerfile

Inside apt-get install it breaks the installation of the packages after it.

move comment about php7.4-xdebug down

---

php74/Dockerfile

php-dev started pointing to php8.0-dev recently

explicitly install php7.4-dev

---

nginx/conf/default.conf

The configuration for BitrixVM is not published anywhere, so I set up a machine with it and downloaded the Nginx configuration in order to figure out what is missing from our configuration.
Example of blocked URLs:
- /bitrix/html_pages/.config.php
- /bitrix/html_pages/.config.php

Bump denies list from BitrixVM nginx configuration

---

nginx/conf/default.conf

Nginx documentation:
> The return directive is the simpler of the two general‑purpose directives and for that reason we recommend using it instead of rewrite when possible

Simplify rewrite of index.php in Nginx

---

README.md

I'm using Memcached composite for Bitrix in my project and I thought that adding its Nginx code there would complicate this project without benefits for the developers using it , so instead this PR just mentions where can you check Memcached settings for users who are interested in it.

Add a note about memcached to readme

---

php73/Dockerfile
php73/php.ini

В последних обновлениях битрикса используется php7.3. Думаю, такой контейнер будет не лишний

#feat add dockerfile with php7.3

---

docker-compose.yml

Не стоит явно открывать наружу порт для php-fpm, достаточно того, что он экспоузится. Nginx видет его внутри сети и может по нему обращаться

Убрал открытие порта в php по умолчанию

---

install.sh

При проверке существования команд git, docker, docker-compose скрипт падал с ошибкой [: hash: unary operator expected. Было в [issue](https://github.com/bitrixdock/bitrixdock/issues/91#issuecomment-734738510).
Данный pull request решает эту проблему.

install.sh исправлен баг проверки установленных команд

---

.env_template
php81/Dockerfile
php81/php.ini

Мне удалось запустить сайт на битриксе на PHP 8.1 с последними обновами 😁
Но пока в проде не советую обновляться, у битрикса все еще есть ошибки и неисправленные тикеты по совместимости с PHP 8.1

Добавлен конфиг PHP 8.1

---

php56/php.ini
php71/php.ini
php73/php.ini
php74/php.ini
php80/php.ini
php81/Dockerfile
php81/php.ini

Со старым mycrypt в PHP 8.1 ловил ошибки в консоле:
+ Отключил вывод варнингов и депрекейтов по умолчанию (при желании их можно посмотреть в админке /bitrix/admin/perfmon_error_list.php?lang=ru или вывести в свой лог)

Правки PHP

---

docker-compose.yml

Привет :)
Т.к. в основном люди используют bitrixdock для разработки - предлагаю поменять [restart policy](https://docs.docker.com/config/containers/start-containers-automatically/) с always на unless-stopped. Это позволит более гибко и удобно управлять проектами (docker compose) тушить/поднимать их, если на тачке более одного проекта. А restart: always нужен для прода

Изменен restart policy

---

php82/Dockerfile

С текущим конфигом mcrypt не устанавливается:
```
root@b09a3ae452c2:/var/www/bitrix# pecl install mcrypt-1.0.5
pecl/mcrypt requires PHP (version >= 7.2.0, version <= 8.2.0, excluded versions: 8.2.0), installed version is 8.2.3
No valid packages found
install failed
```
Возможно, это работало, пока версию php не подняли (текущая 8.2.3). С [mcrypt-1.0.6](https://pecl.php.net/package/mcrypt) все работает корректно

mcrypt-1.0.6 для актуальной версии образа с php 8.2

---

php80/php.ini
php81/php.ini
php82/php.ini

It gave me a 30% page generation time decrease on the production project (1.0s -> 0.7s)
Won't enable when XDebug is enabled; JIT settings will be ignored then.
Articles about JIT: https://medium.com/@edouard.courty/make-your-php-8-apps-twice-as-fast-opcache-jit-8d3542276595, https://stitcher.io/blog/php-8-jit-setup

Enable JIT for PHP 8.0+

---

php80/Dockerfile
php80/php.ini
php81/Dockerfile
php81/php.ini
php82/Dockerfile
php82/php.ini

Не знаю для чего мы раньше компилили его через pecl, но сейчас php-mcrypt включен в репку и можно подтянуть его оттуда, причем сразу актуальную версию
плюс чуток прибрался в файликах

Изменена установка mcrypt

---

README.md

На некоторых машинах встретил такую ошибку в php-fpm контейнере при попытке запуска.
_php fpm failed to create new listening socket: socket(): Address family not supported by protocol (97) 2023-10-03T13:35:49.361278023Z [03-Oct-2023 16:35:49] ERROR: FPM initialization failed_
Решением оказалось включение поддержки IPv6 в системе. Я работал в Ubuntu 22.04.3 LTS, x86_64 Linux 6.2.0-34-generic. Чтобы включить поддержку IPv6  пришлось закомментировать строку в конфиге GRUB, и проблема исчезла.
nano /etc/default/grub
`#GRUB_CMDLINE_LINUX="ipv6.disable=1`

Исправление ошибки контейнера php-fpm при инициализации сокета.

---

apache/Dockerfile

Старый образ не обновлялся 6 лет
Фиксит этот issue https://github.com/bitrixdock/bitrixdock/issues/143

Фикс базового образа apache

---

Makefile
README.md
install.sh
install.wsl.sh

Both are used currently, but keeping both doesn't make sense. Automatic installation is recommended via curl, so curl is supposed to be installed on the user's machine.
Fix for #190.

Switch all wget usages to curl

---

php/php83/Dockerfile
php/php83/php.ini

Previously, mcrypt was not available for php 8.3. It is important to do it in the same manner as otherwise, configs are incompatible.

Install mcrypt from package for php 8.3

---

docker-compose.yml

По умолчанию docker compose берет значение переменной `COMPOSE_PROJECT_NAME`  + имя сервиса в качестве названия для контейнера. Внутри проекта сервисы обращаются друг к другу по имени сервиса. 
Если хардкодить `conainer_name`, то невозможно будет поднять несколько проектов паралельно:

Удален container_name

---

docker-compose.yml
mysql/Dockerfile
mysql/my.cnf

Я заметил такое же поведение https://github.com/bitrixdock/bitrixdock/issues/244 на тяжелых проектах
Оказывается для WSL докер хранит named volumes [внутри VHDX диска](https://docs.docker.com/desktop/features/wsl/best-practices/)
Который находится тут
`%USERPROFILE%\AppData\Local\Docker\wsl\disk\docker_data.vhdx`
И монтируется сюда
`\\wsl.localhost\docker-desktop\mnt\docker-desktop-disk\data\docker\volumes`
Из-за этого база работает **очень медленно**
Я перенес volume внутрь WSL (в папку по умолчанию, где они должны создаваться в нативном Linux) и немного подтюнил базу. Скорость чтения / записи ускорилась минимум в 10 раз на WSL2

Рефакторинг и оптимизация настроек БД

---

docker-compose.yml
nginx/conf/default.conf
nginx/conf/nginx.conf

Добавил:
1.  готовый образ пуш сервера, спасибо `ikarpovich/bitrix-push-server`
2. убрал ненужный if который вносил side-effect 
3. конфиги для резолвинга хоста `bitrix.local` между контейнерами, необходимо для отправки сообщений из php контейнера в контейнер с пуш сервером через nginx

feat: добавлен push-server

---

docker-compose.yml

В случае, если push-сервер не запущен, контейнер `web_server` аварийно завершается с ошибкой:
```
nginx: [emerg] host not found in upstream "push-server-pub" in /etc/nginx/conf.d/default.conf:102
```

Фикс резолва IP адреса при поднятии проекта без push сервера

---

percona/Dockerfile

Начиная с какой-то версии mysql нельзя запускать из под рута
```
2025-06-16T18:17:35.954408Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.42-33) starting as process 1
2025-06-16T18:17:35.955411Z 0 [ERROR] [MY-010123] [Server] Fatal error: Please read "Security" section of the manual to find out how to run mysqld as root!
2025-06-16T18:17:35.955458Z 0 [ERROR] [MY-010119] [Server] Aborting
```

Фикс percona контейнера
